# Generated by Django 4.2.13 on 2026-05-03 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_remarks', models.CharField(blank=True, max_length=200, verbose_name='PO Remarks')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('sorting', models.CharField(blank=True, max_length=200, verbose_name='Sorting')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Company (CBC)')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Entry Date')),
                ('country', models.CharField(blank=True, default='USA', max_length=50)),
                ('record_created_by', models.CharField(blank=True, max_length=150, verbose_name='Record Created By')),
                ('msa_po_signed_by', models.CharField(blank=True, max_length=150, verbose_name='MSA/PO Signed By')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('recruitment_manager', models.CharField(blank=True, max_length=150)),
                ('candidate_name', models.CharField(max_length=200, verbose_name='Candidate Name')),
                ('candidate_email', models.EmailField(blank=True, max_length=254, verbose_name='Candidate Email ID')),
                ('candidate_phone', models.CharField(blank=True, max_length=50, verbose_name='Candidate Phone')),
                ('candidate_pay_type', models.CharField(blank=True, choices=[('w2', 'W2'), ('c2c', 'C2C'), ('na', 'NA')], max_length=10)),
                ('candidate_relationship_mgr', models.CharField(blank=True, max_length=150, verbose_name='Candidate Relationship Manager')),
                ('candidate_visa', models.CharField(blank=True, max_length=20, verbose_name='Candidate Visa')),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('invoice_start_month', models.CharField(blank=True, max_length=20, verbose_name='Invoice Start Month')),
                ('invoice_start_dt', models.DateField(blank=True, null=True, verbose_name='Invoice Start DT')),
                ('active_invoice_begin', models.DateField(blank=True, null=True, verbose_name='Active Invoice Begin Date')),
                ('active_invoice_end', models.DateField(blank=True, null=True, verbose_name='Active Invoice End Date')),
                ('invoice_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending')], default='active', max_length=20, verbose_name='Invoice Status')),
                ('invoice_end_dt', models.DateField(blank=True, null=True, verbose_name='Invoice End DT')),
                ('invoice_schedule', models.CharField(blank=True, max_length=50, verbose_name='Invoice Schedule')),
                ('invoice_email', models.EmailField(blank=True, max_length=254, verbose_name='Invoice Email ID')),
                ('po_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='PO Status')),
                ('po_end_date', models.DateField(blank=True, null=True, verbose_name='PO End Date')),
                ('po_comments', models.TextField(blank=True, verbose_name='PO Comments')),
                ('contract_info_path', models.TextField(blank=True, verbose_name='Contract Information Path')),
                ('billing_type', models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('fixed', 'Fixed'), ('monthly', 'Monthly')], max_length=20)),
                ('bill_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bill Rate')),
                ('candidate_payrate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Candidate Payrate (if hourly)')),
                ('referral_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_payment_terms', models.IntegerField(blank=True, null=True, verbose_name='Net Payment Terms (days)')),
                ('billable_client_name', models.CharField(blank=True, max_length=200, verbose_name='Billable Client Name')),
                ('billable_client_person', models.CharField(blank=True, max_length=150, verbose_name='Billable Client Person Name')),
                ('billable_client_email', models.EmailField(blank=True, max_length=254, verbose_name='Billable Client Person Email')),
                ('billable_client_phone', models.CharField(blank=True, max_length=30, verbose_name='Billable Client Person Phone')),
                ('billable_client_address', models.TextField(blank=True, verbose_name='Billable Client Address')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='Supplier Name')),
                ('second_customer', models.CharField(blank=True, max_length=200, verbose_name='2nd Customer Staffing Company')),
                ('system_integrator', models.CharField(blank=True, max_length=200, verbose_name='System Integrator Name')),
                ('end_client_name', models.CharField(blank=True, max_length=200, verbose_name='End Client Name')),
                ('end_client_person', models.CharField(blank=True, max_length=150, verbose_name='End Client Person Name')),
                ('end_client_email', models.EmailField(blank=True, max_length=254, verbose_name='End Client Person Email')),
                ('end_client_phone', models.CharField(blank=True, max_length=30, verbose_name='End Client Person Phone')),
                ('customer_type', models.CharField(blank=True, choices=[('investment_firm', 'Investment Firm'), ('medical_insurance', 'Medical Insurance'), ('pharma', 'Pharma'), ('technology', 'Technology'), ('finance', 'Finance'), ('retail', 'Retail'), ('other', 'Other')], max_length=30)),
                ('first_customer', models.CharField(blank=True, max_length=200, verbose_name='First Customer')),
                ('work_location_type', models.CharField(blank=True, choices=[('remote', 'Remote'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid')], max_length=20)),
                ('work_location_state', models.CharField(blank=True, max_length=100)),
                ('work_location_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
    ]
