# Generated by Django 4.2.13 on 2026-05-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='candidate_address',
            field=models.TextField(blank=True, verbose_name='Candidate Residential Address'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='candidate_dob',
            field=models.DateField(blank=True, null=True, verbose_name='Candidate DOB'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='candidate_ssn',
            field=models.CharField(blank=True, max_length=20, verbose_name='SSN'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='po_docs/', verbose_name='Upload Document'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='implementation_partner',
            field=models.CharField(blank=True, max_length=200, verbose_name='Implementation Partner'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='mutually_executed',
            field=models.BooleanField(default=False, verbose_name='Mutually Executed'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='net_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Net Pay'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='pay_when_paid',
            field=models.BooleanField(default=False, verbose_name='Pay When Paid'),
        ),
    ]
