# Generated by Django 4.2.13 on 2026-05-07 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200, verbose_name='Vendor Name')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Client Name')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='Supplier Name')),
                ('fein_number', models.CharField(blank=True, max_length=50, verbose_name='FEIN Number')),
                ('vendor_address', models.TextField(blank=True, verbose_name='Vendor Address')),
                ('mutually_executed', models.BooleanField(default=False, verbose_name='Mutually Executed')),
                ('date_of_execution', models.DateField(blank=True, null=True, verbose_name='Date of Execution')),
                ('msa_validity', models.CharField(blank=True, choices=[('long_term', 'Long Term'), ('short_term', 'Short Term'), ('annual', 'Annual'), ('custom', 'Custom Dates')], max_length=20, verbose_name='MSA Validity')),
                ('msa_start_date', models.DateField(blank=True, null=True, verbose_name='MSA Start Date')),
                ('msa_end_date', models.DateField(blank=True, null=True, verbose_name='MSA End Date')),
                ('poc_signatory', models.CharField(blank=True, max_length=150, verbose_name='POC Name of Signatory')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='msa_docs/', verbose_name='MSA Document')),
                ('accounts_poc_name', models.CharField(blank=True, max_length=150, verbose_name='Accounts POC Name')),
                ('accounts_poc_email', models.EmailField(blank=True, max_length=254, verbose_name='Accounts POC Email')),
                ('accounts_poc_phone', models.CharField(blank=True, max_length=30, verbose_name='Accounts POC Phone')),
                ('vendor_poc1_name', models.CharField(blank=True, max_length=150, verbose_name='Vendor POC 1 Name')),
                ('vendor_poc1_email', models.EmailField(blank=True, max_length=254, verbose_name='Vendor POC 1 Email')),
                ('vendor_poc1_phone', models.CharField(blank=True, max_length=30, verbose_name='Vendor POC 1 Phone')),
                ('vendor_poc2_name', models.CharField(blank=True, max_length=150, verbose_name='Vendor POC 2 Name')),
                ('vendor_poc2_email', models.EmailField(blank=True, max_length=254, verbose_name='Vendor POC 2 Email')),
                ('vendor_poc2_phone', models.CharField(blank=True, max_length=30, verbose_name='Vendor POC 2 Phone')),
                ('vendor_poc3_name', models.CharField(blank=True, max_length=150, verbose_name='Vendor POC 3 Name')),
                ('vendor_poc3_email', models.EmailField(blank=True, max_length=254, verbose_name='Vendor POC 3 Email')),
                ('vendor_poc3_phone', models.CharField(blank=True, max_length=30, verbose_name='Vendor POC 3 Phone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msas_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MSA',
                'verbose_name_plural': 'MSAs',
                'ordering': ['-created_at'],
            },
        ),
    ]
