# Generated by Django 4.2.13 on 2026-05-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_options_alter_employee_first_name_and_more'),
        ('msa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msa',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msas', to='employees.employee', verbose_name='Employee (HR)'),
        ),
    ]
