# Generated by Django 4.2.13 on 2026-05-03 17:25

import apps.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR')], default='hr', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False, help_text='Admins are auto-approved on signup. HRs require Admin approval.')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('emp_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('official_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('worksite_address', models.TextField(blank=True)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('exited', 'Exited'), ('bench', 'Bench')], default='active', max_length=20)),
                ('employment_type', models.CharField(blank=True, choices=[('w2', 'W2'), ('c2c', 'C2C'), ('1099', '1099'), ('fulltime', 'Full Time')], max_length=20)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('employer', models.CharField(blank=True, max_length=150)),
                ('primary_skills', models.TextField(blank=True)),
                ('secondary_skills', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('visa_type', models.CharField(blank=True, choices=[('GC', 'Green Card'), ('USC', 'US Citizen'), ('H1B', 'H1B'), ('L1', 'L1'), ('OPT', 'OPT'), ('CPT', 'CPT'), ('TN', 'TN'), ('other', 'Other')], max_length=10)),
                ('id_status', models.CharField(blank=True, max_length=100)),
                ('e_verify_status', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.accounts.models._generate_otp, max_length=6)),
                ('expires_at', models.DateTimeField(default=apps.accounts.models._otp_expiry)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
