# Generated by Django 4.2.13 on 2026-05-03 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adf_employee_name', models.CharField(max_length=200, verbose_name='ADP Employee Name')),
                ('emp_no', models.CharField(max_length=50, unique=True, verbose_name='Emp No')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('dob', models.DateField(verbose_name='DOB')),
                ('retirement_dob', models.DateField(blank=True, null=True, verbose_name='Rehire DOJ')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('official_email', models.EmailField(max_length=254, verbose_name='Official Mail ID')),
                ('personal_email', models.EmailField(max_length=254, verbose_name='Personal Email ID')),
                ('address', models.TextField(verbose_name='Address')),
                ('worksite_address', models.TextField(verbose_name='Worksite Address / Location 1')),
                ('status', models.CharField(choices=[('active', 'Active'), ('exited', 'Exited'), ('bench', 'Bench')], default='active', max_length=10, verbose_name='Status')),
                ('employment_type', models.CharField(choices=[('w2', 'W2'), ('c2c', 'C2C'), ('1099', '1099'), ('fulltime', 'Full Time')], max_length=20, verbose_name='Employment Type')),
                ('date_of_joining', models.DateField(blank=True, null=True, verbose_name='DOJ')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='Exit Date')),
                ('employer', models.CharField(blank=True, max_length=150, verbose_name='Employer')),
                ('designation', models.CharField(blank=True, max_length=150, verbose_name='Designation')),
                ('primary_skills', models.TextField(blank=True, verbose_name='Primary Skills')),
                ('secondary_skills', models.TextField(blank=True, verbose_name='Secondary Skills')),
                ('location', models.CharField(max_length=150, verbose_name='Location')),
                ('visa_type', models.CharField(choices=[('GC', 'Green Card'), ('USC', 'US Citizen'), ('H1B', 'H1B'), ('L1', 'L1'), ('OPT', 'OPT'), ('CPT', 'CPT'), ('TN', 'TN'), ('other', 'Other')], max_length=10, verbose_name='Visa Type')),
                ('id_status', models.CharField(choices=[('compliant', 'Compliant'), ('pending', 'Pending'), ('expired', 'Expired'), ('na', 'N/A')], max_length=20, verbose_name='ID Status')),
                ('e_verify_status', models.CharField(choices=[('compliant', 'Compliant'), ('applied', 'Applied'), ('pending', 'Pending'), ('na', 'N/A')], max_length=20, verbose_name='E-Verify Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['adf_employee_name'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(blank=True, max_length=150)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('employment_type', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('worksite_address', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('primary_skills', models.TextField(blank=True)),
                ('secondary_skills', models.TextField(blank=True)),
                ('visa_type', models.CharField(blank=True, max_length=10)),
                ('id_status', models.CharField(blank=True, max_length=20)),
                ('e_verify_status', models.CharField(blank=True, max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='employees.employee')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employment History',
                'verbose_name_plural': 'Employment Histories',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
