from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_name_data(apps, schema_editor):
    """Copy adf_employee_name → first_name for existing records."""
    Employee = apps.get_model("employees", "Employee")
    for emp in Employee.objects.all():
        if emp.adf_employee_name:
            emp.first_name = emp.adf_employee_name
            emp.last_name  = ""
            emp.save(update_fields=["first_name", "last_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Add new name fields (nullable first so migration doesn't fail on existing rows)
        migrations.AddField(
            model_name="employee",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="First Name"),
        ),
        migrations.AddField(
            model_name="employee",
            name="middle_name",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Middle Name"),
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Last Name"),
        ),

        # 2. Copy adf_employee_name → first_name
        migrations.RunPython(migrate_name_data, migrations.RunPython.noop),

        # 3. Remove old field
        migrations.RemoveField(model_name="employee", name="adf_employee_name"),

        # 4. Add client & customer to Employee
        migrations.AddField(
            model_name="employee",
            name="client",
            field=models.CharField(blank=True, max_length=150, verbose_name="Client"),
        ),
        migrations.AddField(
            model_name="employee",
            name="customer",
            field=models.CharField(blank=True, max_length=150, verbose_name="Customer"),
        ),

        # 5. Add client & customer to EmploymentHistory
        migrations.AddField(
            model_name="employmenthistory",
            name="client",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="employmenthistory",
            name="customer",
            field=models.CharField(blank=True, max_length=150),
        ),

        # 6. Update location field — increase max_length & add choices
        migrations.AlterField(
            model_name="employee",
            name="location",
            field=models.CharField(
                choices=[
                    ("Alabama", "Alabama"), ("Alaska", "Alaska"), ("Arizona", "Arizona"),
                    ("Arkansas", "Arkansas"), ("California", "California"), ("Colorado", "Colorado"),
                    ("Connecticut", "Connecticut"), ("Delaware", "Delaware"), ("Florida", "Florida"),
                    ("Georgia", "Georgia"), ("Hawaii", "Hawaii"), ("Idaho", "Idaho"),
                    ("Illinois", "Illinois"), ("Indiana", "Indiana"), ("Iowa", "Iowa"),
                    ("Kansas", "Kansas"), ("Kentucky", "Kentucky"), ("Louisiana", "Louisiana"),
                    ("Maine", "Maine"), ("Maryland", "Maryland"), ("Massachusetts", "Massachusetts"),
                    ("Michigan", "Michigan"), ("Minnesota", "Minnesota"), ("Mississippi", "Mississippi"),
                    ("Missouri", "Missouri"), ("Montana", "Montana"), ("Nebraska", "Nebraska"),
                    ("Nevada", "Nevada"), ("New Hampshire", "New Hampshire"), ("New Jersey", "New Jersey"),
                    ("New Mexico", "New Mexico"), ("New York", "New York"),
                    ("North Carolina", "North Carolina"), ("North Dakota", "North Dakota"),
                    ("Ohio", "Ohio"), ("Oklahoma", "Oklahoma"), ("Oregon", "Oregon"),
                    ("Pennsylvania", "Pennsylvania"), ("Rhode Island", "Rhode Island"),
                    ("South Carolina", "South Carolina"), ("South Dakota", "South Dakota"),
                    ("Tennessee", "Tennessee"), ("Texas", "Texas"), ("Utah", "Utah"),
                    ("Vermont", "Vermont"), ("Virginia", "Virginia"), ("Washington", "Washington"),
                    ("Washington D.C.", "Washington D.C."), ("West Virginia", "West Virginia"),
                    ("Wisconsin", "Wisconsin"), ("Wyoming", "Wyoming"),
                    ("Puerto Rico", "Puerto Rico"), ("Guam", "Guam"),
                    ("Afghanistan", "Afghanistan"), ("Albania", "Albania"), ("Algeria", "Algeria"),
                    ("Argentina", "Argentina"), ("Armenia", "Armenia"), ("Australia", "Australia"),
                    ("Austria", "Austria"), ("Azerbaijan", "Azerbaijan"), ("Bahrain", "Bahrain"),
                    ("Bangladesh", "Bangladesh"), ("Belarus", "Belarus"), ("Belgium", "Belgium"),
                    ("Bolivia", "Bolivia"), ("Brazil", "Brazil"), ("Bulgaria", "Bulgaria"),
                    ("Cambodia", "Cambodia"), ("Canada", "Canada"), ("Chile", "Chile"),
                    ("China", "China"), ("Colombia", "Colombia"), ("Croatia", "Croatia"),
                    ("Czech Republic", "Czech Republic"), ("Denmark", "Denmark"),
                    ("Ecuador", "Ecuador"), ("Egypt", "Egypt"), ("Estonia", "Estonia"),
                    ("Ethiopia", "Ethiopia"), ("Finland", "Finland"), ("France", "France"),
                    ("Germany", "Germany"), ("Ghana", "Ghana"), ("Greece", "Greece"),
                    ("Guatemala", "Guatemala"), ("Honduras", "Honduras"), ("Hong Kong", "Hong Kong"),
                    ("Hungary", "Hungary"), ("India", "India"), ("Indonesia", "Indonesia"),
                    ("Iran", "Iran"), ("Iraq", "Iraq"), ("Ireland", "Ireland"),
                    ("Israel", "Israel"), ("Italy", "Italy"), ("Japan", "Japan"),
                    ("Jordan", "Jordan"), ("Kazakhstan", "Kazakhstan"), ("Kenya", "Kenya"),
                    ("Kuwait", "Kuwait"), ("Latvia", "Latvia"), ("Lebanon", "Lebanon"),
                    ("Libya", "Libya"), ("Lithuania", "Lithuania"), ("Malaysia", "Malaysia"),
                    ("Mexico", "Mexico"), ("Morocco", "Morocco"), ("Myanmar", "Myanmar"),
                    ("Nepal", "Nepal"), ("Netherlands", "Netherlands"), ("New Zealand", "New Zealand"),
                    ("Nigeria", "Nigeria"), ("Norway", "Norway"), ("Oman", "Oman"),
                    ("Pakistan", "Pakistan"), ("Panama", "Panama"), ("Peru", "Peru"),
                    ("Philippines", "Philippines"), ("Poland", "Poland"), ("Portugal", "Portugal"),
                    ("Qatar", "Qatar"), ("Romania", "Romania"), ("Russia", "Russia"),
                    ("Saudi Arabia", "Saudi Arabia"), ("Serbia", "Serbia"), ("Singapore", "Singapore"),
                    ("Slovakia", "Slovakia"), ("Slovenia", "Slovenia"), ("South Africa", "South Africa"),
                    ("South Korea", "South Korea"), ("Spain", "Spain"), ("Sri Lanka", "Sri Lanka"),
                    ("Sweden", "Sweden"), ("Switzerland", "Switzerland"), ("Syria", "Syria"),
                    ("Taiwan", "Taiwan"), ("Thailand", "Thailand"), ("Tunisia", "Tunisia"),
                    ("Turkey", "Turkey"), ("UAE", "UAE"), ("Ukraine", "Ukraine"),
                    ("United Kingdom", "United Kingdom"), ("United States", "United States"),
                    ("Uruguay", "Uruguay"), ("Uzbekistan", "Uzbekistan"), ("Venezuela", "Venezuela"),
                    ("Vietnam", "Vietnam"), ("Yemen", "Yemen"), ("Zimbabwe", "Zimbabwe"),
                    ("Other", "Other"),
                ],
                max_length=200,
                verbose_name="Location",
            ),
        ),

        # 7. Update designation field — add choices
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Software Engineer", "Software Engineer"),
                    ("Senior Software Engineer", "Senior Software Engineer"),
                    ("Lead Software Engineer", "Lead Software Engineer"),
                    ("Principal Software Engineer", "Principal Software Engineer"),
                    ("Staff Software Engineer", "Staff Software Engineer"),
                    ("Frontend Developer", "Frontend Developer"),
                    ("Backend Developer", "Backend Developer"),
                    ("Full Stack Developer", "Full Stack Developer"),
                    ("Mobile Developer", "Mobile Developer"),
                    ("iOS Developer", "iOS Developer"),
                    ("Android Developer", "Android Developer"),
                    ("DevOps Engineer", "DevOps Engineer"),
                    ("Cloud Engineer", "Cloud Engineer"),
                    ("Site Reliability Engineer (SRE)", "Site Reliability Engineer (SRE)"),
                    ("Infrastructure Engineer", "Infrastructure Engineer"),
                    ("Network Engineer", "Network Engineer"),
                    ("Security Engineer", "Security Engineer"),
                    ("Database Administrator (DBA)", "Database Administrator (DBA)"),
                    ("System Administrator", "System Administrator"),
                    ("IT Support Specialist", "IT Support Specialist"),
                    ("IT Manager", "IT Manager"),
                    ("Data Engineer", "Data Engineer"),
                    ("Data Scientist", "Data Scientist"),
                    ("Machine Learning Engineer", "Machine Learning Engineer"),
                    ("AI/ML Engineer", "AI/ML Engineer"),
                    ("BI Developer", "BI Developer"),
                    ("QA Engineer", "QA Engineer"),
                    ("Senior QA Engineer", "Senior QA Engineer"),
                    ("QA Lead", "QA Lead"),
                    ("Automation Engineer (SDET)", "Automation Engineer (SDET)"),
                    ("Solutions Architect", "Solutions Architect"),
                    ("Enterprise Architect", "Enterprise Architect"),
                    ("Cloud Architect", "Cloud Architect"),
                    ("Technical Lead", "Technical Lead"),
                    ("Engineering Manager", "Engineering Manager"),
                    ("VP of Engineering", "VP of Engineering"),
                    ("Chief Technology Officer (CTO)", "Chief Technology Officer (CTO)"),
                    ("UI/UX Designer", "UI/UX Designer"),
                    ("Product Designer", "Product Designer"),
                    ("Project Manager", "Project Manager"),
                    ("Senior Project Manager", "Senior Project Manager"),
                    ("Program Manager", "Program Manager"),
                    ("Portfolio Manager", "Portfolio Manager"),
                    ("Delivery Manager", "Delivery Manager"),
                    ("Scrum Master", "Scrum Master"),
                    ("Agile Coach", "Agile Coach"),
                    ("Product Owner", "Product Owner"),
                    ("Business Analyst", "Business Analyst"),
                    ("Senior Business Analyst", "Senior Business Analyst"),
                    ("Functional Consultant", "Functional Consultant"),
                    ("ERP Consultant", "ERP Consultant"),
                    ("SAP Consultant", "SAP Consultant"),
                    ("Salesforce Consultant", "Salesforce Consultant"),
                    ("Product Manager", "Product Manager"),
                    ("Senior Product Manager", "Senior Product Manager"),
                    ("HR Executive", "HR Executive"),
                    ("HR Specialist", "HR Specialist"),
                    ("HR Generalist", "HR Generalist"),
                    ("HR Manager", "HR Manager"),
                    ("Senior HR Manager", "Senior HR Manager"),
                    ("Talent Acquisition Specialist", "Talent Acquisition Specialist"),
                    ("Recruiter", "Recruiter"),
                    ("Senior Recruiter", "Senior Recruiter"),
                    ("Technical Recruiter", "Technical Recruiter"),
                    ("HR Business Partner", "HR Business Partner"),
                    ("Compensation & Benefits Specialist", "Compensation & Benefits Specialist"),
                    ("Learning & Development Specialist", "Learning & Development Specialist"),
                    ("HR Director", "HR Director"),
                    ("VP of Human Resources", "VP of Human Resources"),
                    ("Chief People Officer (CPO)", "Chief People Officer (CPO)"),
                    ("Payroll Specialist", "Payroll Specialist"),
                    ("Payroll Manager", "Payroll Manager"),
                    ("HRIS Analyst", "HRIS Analyst"),
                    ("Financial Analyst", "Financial Analyst"),
                    ("Senior Financial Analyst", "Senior Financial Analyst"),
                    ("Accountant", "Accountant"),
                    ("Senior Accountant", "Senior Accountant"),
                    ("Finance Manager", "Finance Manager"),
                    ("Controller", "Controller"),
                    ("Chief Financial Officer (CFO)", "Chief Financial Officer (CFO)"),
                    ("Sales Executive", "Sales Executive"),
                    ("Business Development Manager", "Business Development Manager"),
                    ("Account Manager", "Account Manager"),
                    ("Key Account Manager", "Key Account Manager"),
                    ("Account Executive", "Account Executive"),
                    ("Sales Manager", "Sales Manager"),
                    ("VP of Sales", "VP of Sales"),
                    ("Marketing Specialist", "Marketing Specialist"),
                    ("Digital Marketing Manager", "Digital Marketing Manager"),
                    ("Content Manager", "Content Manager"),
                    ("Marketing Director", "Marketing Director"),
                    ("VP of Marketing", "VP of Marketing"),
                    ("Operations Manager", "Operations Manager"),
                    ("Director of Operations", "Director of Operations"),
                    ("VP of Operations", "VP of Operations"),
                    ("Chief Operating Officer (COO)", "Chief Operating Officer (COO)"),
                    ("Chief Executive Officer (CEO)", "Chief Executive Officer (CEO)"),
                    ("General Manager", "General Manager"),
                    ("Director", "Director"),
                    ("Senior Director", "Senior Director"),
                    ("Vice President (VP)", "Vice President (VP)"),
                    ("Senior Vice President (SVP)", "Senior Vice President (SVP)"),
                    ("Administrative Assistant", "Administrative Assistant"),
                    ("Executive Assistant", "Executive Assistant"),
                    ("Office Manager", "Office Manager"),
                    ("Legal Counsel", "Legal Counsel"),
                    ("Compliance Officer", "Compliance Officer"),
                    ("Contracts Manager", "Contracts Manager"),
                    ("Trainee / Intern", "Trainee / Intern"),
                    ("Associate Consultant", "Associate Consultant"),
                    ("Consultant", "Consultant"),
                    ("Senior Consultant", "Senior Consultant"),
                    ("Principal Consultant", "Principal Consultant"),
                    ("Managing Consultant", "Managing Consultant"),
                    ("Other", "Other"),
                ],
                max_length=200,
                verbose_name="Designation",
            ),
        ),

        # 8. Update employer default
        migrations.AlterField(
            model_name="employee",
            name="employer",
            field=models.CharField(default="CBC Labs", max_length=150, verbose_name="Employer"),
        ),
    ]
