# Generated by Django 4.2.13 on 2026-05-03 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=50, unique=True, verbose_name='Candidate ID')),
                ('candidate_full_name', models.CharField(max_length=200, verbose_name='Candidate Full Name')),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('personal_email', models.EmailField(max_length=254, verbose_name='Personal Email ID')),
                ('current_location', models.CharField(blank=True, max_length=150)),
                ('preferred_work_location', models.CharField(blank=True, max_length=150)),
                ('offer_released_date', models.DateField(blank=True, null=True)),
                ('offer_type', models.CharField(blank=True, choices=[('w2', 'W2'), ('c2c', 'C2C'), ('intern', 'Intern'), ('na', 'NA')], max_length=20)),
                ('employment_type', models.CharField(blank=True, choices=[('fulltime', 'Full-Time'), ('contract', 'Contract'), ('parttime', 'Part-Time'), ('intern', 'Internship')], max_length=20)),
                ('visa_type', models.CharField(blank=True, choices=[('H1B', 'H1B'), ('GC', 'Green Card'), ('USC', 'US Citizen'), ('OPT', 'OPT'), ('CPT', 'CPT'), ('L1', 'L1'), ('TN', 'TN'), ('F1', 'F1'), ('other', 'Other')], max_length=10)),
                ('offer_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('no_show', 'No Show'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('no_show_reason', models.TextField(blank=True)),
                ('hr_remarks', models.TextField(blank=True)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('technology', models.CharField(blank=True, max_length=150)),
                ('work_mode', models.CharField(blank=True, choices=[('remote', 'Remote'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid')], max_length=20)),
                ('rate_type', models.CharField(blank=True, choices=[('annual', 'Annual'), ('hourly', 'Hourly')], max_length=20)),
                ('salary_pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True, verbose_name='DOJ')),
                ('recruiter_name', models.CharField(blank=True, max_length=150)),
                ('account_manager', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
